{% set name = "pytest-arraydiff" %}
{% set version = "0.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 70e2a9183af5b4f05f694727beb30eb5fc6712632b240ef259ec60984a629b1a

build:
  number: 0
  script: python -m pip install . --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0.1
    - setuptools_scm
  run:
    - python
    - pytest >=6.2
    - numpy

# Worked locally, but not on CI
# >   assert code == 0
# E   assert 4 == 0
{% set deselect_tests = " --deselect=tests/test_pytest_arraydiff.py::test_generate" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_pytest_arraydiff.py::test_default_format" %}
# Test never finished on Windows
{% set deselect_tests = deselect_tests + " --deselect=tests/test_pytest_arraydiff.py::test_fails" %}  # [win]
test:
  source_files:
    - tests
  imports:
    - pytest_arraydiff
  commands:
    - pip check
    - pytest -v tests {{ deselect_tests }}
  requires:
    - pip
    - astropy
    - pandas

about:
  home: https://pypi.org/project/pytest-arraydiff
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pytest plugin to help with comparing array output from tests
  description: |
    This is a py.test plugin to facilitate the generation and comparison of
    data arrays produced during tests.
  doc_url: https://pypi.org/project/pytest-arraydiff
  dev_url: https://github.com/astropy/pytest-arraydiff

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - drdavella
    - mwcraig
