travis:
  secure:
    BINSTAR_TOKEN: mBn5PaFaO6DNDSUs2Qs+odiZin6ScULk2ZtcBKCcmt8OB1fyGcatcNA9WRK4aJ+7X3FVuFCsweiKlU4HnhweDR5h76O3xYsZb+2sD+sgbbzhphG6FDD8m/gl6fsDjem7eRetu24K17ocmlFUlhN3vCdJl0gDNa183LBlBLYBQcG3dX01mdHro1+5FVjjhNnZohsqhmqOIJzOfOEpYMTaQqbhtjuSty8Amr0B2vWIRJtlSIOddXrcC9qJwv+SojXG/7FatattW0gG/cof2mDMenNMqQfw0nmxKkaUQDRRgN1w78qpFU4Ph5YZsJv+y2JQbw7t0lRURlECZh1vr5QSbceGn3pQ+L2PPClRpq4V/zhEcW3ELWu54O/8dgo2GjVS1WOXmd4hynZuiK5i1zFKAH9hA0Glck3EyIZLA7+jYijvjh5ivQ27Pq0CJGFd0c65rerEn9aT5ScRV4CPTrvIJDKJNQDI0udJdpiJv2FCYG+d7v8fEdJlME7O2Ro3DB67MQtHvHoTVRw1KcQVvXGRIMhTW3O034vWyCl1xrnmgH9jRpQ86SA2AeGfH0cBeJZkzNKjz1Xs+s6ykuJifGey5qMr6Ve1fMSUF7IFqJbXQhSUqOMjH60GmfJ4yXW3YIn/LZGpbQ3/yaUcCBJRzB4IF2V3ZB4X1buyUxla92XdFdw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
