travis:
  secure:
    BINSTAR_TOKEN: SKkMVmzTPswIbToS0c4em7Ay7hy/GXYK9QfFR3T+mU+GL4PBrb1MuCbMVZxONTx9jxZI5MLEy0NSxvY7BcvWrVH0CwD59zK3odZJKlAv2HSGdzQuG4enAsGdA5cUdt5WktplvtnQbVTFX5fwcR7bh3nW/OJHpiAHmSsVvpOwmiARVXhMKrK2lRYMuEckYtInPe2MO6YBSbsvAD00Y0MgD/OttJ7oJimDo0hIw9d/rZViTdsLlTdsUF6tdTR7y7OZ8l3oNKklQoYHKuE2zK17mfHs6PdNE4R6AiJ+T1nWX944Sjd1UeoWl4WKDLKEodBmTy5lfd5SvAqt+/So8anz/UT+BA9T04PY0NFZLSrX9n1lX923AZ8qKvDYYiIwmxPhA9PmO9KQyQxodR4mknAX5Wj7Wd9KAtXqMny+PHIvCeDSbQqoA26Dqcerd7CgIH8lXiMNv9qk9fgh8kfykqWxhL0IoFzXxY3TmY/FhI0nfODjXEgtf6wYo4AHyrwAIqxK+4sTMYvC6s2icq7zc8x2tWoXBZhUlsUz1J5INQQiCxWl2maXOaQBagro7Bw3PRrZDtrYzaPyBJdif6rE9sKag9T+DBnTtbm8uJBd+/0aMzF/hChQiwTwiGMjmnXcBez1JCap9Ju2fc/+sy6t73IG0CPL4yvKk+sUdHxx4Z8MTlY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
