travis:
  secure:
    BINSTAR_TOKEN: SeQZhsqe21B8o9rUKkq9ac+2SQiQ0JJToRW1Dk2E+zPPOOasW7Ga8RA7G4kMOvxYZQeRErkpwWLFAwQfcCcQJT6uxeQFsbqspUVBPZ0orSB0joTOuylDu305F6OSogcMTHOcTuZNVHedMOxtWhgDqskV3ujsbGs7UywxedBeRb1DLuv+4OQntauU22zxm9B5J7Re9F/duL46Fsk6MikkSRGkihUoCCOCgj9Q85G9LELV4UbrM1Ema/PtWSpIKOb1A/+iXuZzgOURViSml6zf8giS78CuoBh8mF+77UcFDqz2n1jYBoDIqg9lg7ibBwgKY+hEIG7iMgtbeDj/PXjgCnrBCmNfr8sFDy8XUnxRe6++d2mHhlmtXT2+pLWPBooNu18Mol7cAHh538KyMFjAubIWRAoVLMFAuD+FFsR0psGHFL7C3RdpeRlNmxX6MAqKPr6S0fqElYHDHI9zYYR0Hq0sRduVTxk18EOTLEHStlWZY9Dg8inT4Gnt+bweIzsbcmVjF8pC2JuY8Y9MxZwne4NwLnSP9YHbN61ZBRi93fOPTS3UoqOpoRoU5EIa8fICJQUuDjiVXiZboCk0hfluy8mLwJj/mxagY+qyyx6ha6AOuD9UsdllE8cbqoNcgH4+PkZ1vT0xZQZxmcy4jsh/3DGpk2btVDZVtPQYQAoZJbU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
